ClassLength:
  Max: 120

LineLength:
  Max: 130

MethodLength:
  CountComments: false  # count full line comments?
  Max: 10

Metrics/AbcSize:
  Max: 30

Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/DateTime:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/SafeNavigationChain:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/**/*
    - db/**/*
    - config/**/*
    - Rakefile
    - script/**/*
    - spec/factories/**/*
    - spec/**/*
    - !ruby/regexp /old_and_unused\.rb$/
